package common

import androidx.work.WorkManager
import io.ktor.client.HttpClient
import io.ktor.client.engine.okhttp.OkHttp
import io.ktor.client.request.forms.formData
import io.ktor.client.request.forms.submitFormWithBinaryData
import io.ktor.client.statement.HttpResponse
import io.ktor.client.statement.bodyAsText
import io.ktor.client.utils.EmptyContent.headers
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.headers
import io.ktor.http.isSuccess
import kotlinx.atomicfu.TraceBase.None.append
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import sp.bvantur.inspektify.ktor.AutoDetectTarget
import video.api.uploader.api.work.uploadWithUploadToken
import java.io.File

actual class VideoUploader actual constructor(private val context: Context) {
    /**
     * Returns WorkRequest id as String.
     * Caller should pass uploadToken (token generated by your backend).
     */
    val client = HttpClient(OkHttp)
    actual suspend fun uploadVideo(filePath: String, uploadToken: String): String = withContext(Dispatchers.IO) {
        val file = File(filePath)
        if (!file.exists()) throw IllegalArgumentException("File not found: $filePath")

        val response: HttpResponse = client.submitFormWithBinaryData(
            url = "https://dashboard-ramcek.net2software.net/api/v1/frontend/checkfile",
            formData = formData {
                append("file", file.readBytes(), Headers.build {
                    append(HttpHeaders.ContentType, "video/mp4")
                    append(HttpHeaders.ContentDisposition, "filename=\"${file.name}\"")
                })
            }
        ) {
            headers {
                append(HttpHeaders.Authorization, "Bearer $uploadToken")
            }
        }

        if (response.status.isSuccess()) {
            response.bodyAsText()
        } else {
            throw Exception("Upload failed: ${response.status}")
        }
    }
}