package common

import androidx.work.WorkManager
import com.google.firebase.crashlytics.internal.network.HttpResponse
import io.ktor.client.HttpClient
import io.ktor.client.request.forms.formData
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import sp.bvantur.inspektify.ktor.AutoDetectTarget
import video.api.uploader.api.work.uploadWithUploadToken
import java.io.File

actual class VideoUploader actual constructor(private val context: Context) {
    /**
     * Returns WorkRequest id as String.
     * Caller should pass uploadToken (token generated by your backend).
     */
    actual suspend fun uploadVideo(filePath: String, uploadToken: String): String = withContext(Dispatchers.IO) {
        val myVideoFile = File(filePath)
        val workManager = WorkManager.getInstance(context)

        // uploadWithUploadToken enqueues and returns the WorkRequest id (UUID)
        val workId = workManager.uploadWithUploadToken(uploadToken, myVideoFile)

        // workId is a UUID string; return it so caller can observe or persist
        workId.toString()
    }
}